"""Portable, authorized resource snapshots. See packages/contracts/ddp/bundle-format.md."""

import asyncio
import hashlib
import io
from tempfile import SpooledTemporaryFile

from ddp_core.bundle import (
    IDENTITY,
    MAX_ARCHIVE,
    MAX_FILE,
    MAX_MANIFEST,
    NODE_ID,
    BundleError,
    VerifiedBundle,
    build_bundle,
    digest,
    licence_valid_until as parse_licence_valid_until,
    json_bytes,
    parse_json,
    read_bundle,
    validate_parts,
)
from fastapi import APIRouter, Depends, Header, Request
from fastapi.responses import JSONResponse, Response
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from ddp_corpus import node_identity
from ddp_corpus.config import settings
from ddp_corpus.db import get_session
from ddp_corpus.deps import Actor, current_actor, get_storage
from ddp_corpus.errors import APIError
from ddp_corpus.bundle_models import BundleReplica
from ddp_corpus.models import (
    Chunk,
    Document,
    DocumentUpload,
    Evidence,
    ParseJob,
    Resource,
    ResourceVersion,
    UploadEvent,
    new_id,
)
from ddp_corpus.policy import require_resource
from ddp_corpus.storage import prefix_of

router = APIRouter()


def _bundle_error(exc: BundleError) -> APIError:
    return APIError(
        413 if exc.code == "bundle_too_large" else 422, str(exc), "invalid_request_error", exc.code
    )


async def _version(session, actor, resource_id, version_id):
    resource = await require_resource(session, actor, resource_id)
    version = await session.scalar(
        select(ResourceVersion).where(
            ResourceVersion.id == version_id,
            ResourceVersion.resource_id == resource.id,
            ResourceVersion.deleted_at.is_(None),
        )
    )
    if version is None:
        raise APIError(
            404, "resource version not found", "invalid_request_error", "resource_not_found"
        )
    return resource, version


async def _get_bytes(storage, key: str, maximum: int = MAX_FILE) -> bytes:
    try:
        return await storage.get_limited(key, maximum)
    except ValueError as exc:
        raise BundleError("bundle_too_large", "stored object exceeds bundle limit") from exc
async def _snapshot(session, storage, resource, version) -> VerifiedBundle:
    if version.bundle_prefix:
        # Only prefixes generated by this service can be dereferenced. Manifest filenames
        # never become storage keys before validation.
        expected = f"bundles/{version.id}/"
        if version.bundle_prefix != expected:
            raise APIError(
                409, "invalid stored bundle binding", "server_error", "bundle_binding_invalid"
            )
        raw = await _get_bytes(storage, expected + "manifest.json", MAX_MANIFEST)
        manifest = parse_json(raw)
        if not isinstance(manifest, dict) or not isinstance(manifest.get("source"), dict):
            raise BundleError("bundle_invalid", "invalid stored bundle manifest")
        names = ["layout.json", "evidence.json", "provenance.json"]
        if manifest.get("source", {}).get("original") == "present":
            names.append("source.bin")
        for feature, member in (("wiki", "wiki.json"), ("vectors", "vectors.json")):
            if member in [entry.get("path") for entry in manifest.get("files", []) or []]:
                names.append(member)
        files = {name: await _get_bytes(storage, expected + name) for name in names}
        return validate_parts(manifest, files)

    # Bundle 的来源身份取**唯一那个**节点身份（控制面密钥派生、启动时绑定），
    # 不再直接读 BUNDLE_NODE_ID：两个身份源不一致时导出的 Bundle 会声称自己
    # 出自一个谁也验不了的节点，而且不报错。
    node = node_identity.local_node_id()
    if not NODE_ID.fullmatch(node):
        raise APIError(
            503,
            "configure BUNDLE_NODE_ID to a persistent unique node identity",
            "server_error",
            "node_identity_unconfigured",
        )
    document = await session.get(Document, version.document_id)
    if document is None:
        raise APIError(409, "missing resource document", "server_error", "bundle_binding_invalid")
    source = dict(
        origin_node_id=node,
        authority_node_id=node,
        resource_id=resource.id,
        source_version_id=version.id,
        source_digest="sha256:" + version.source_digest,
        parse_revision=version.parse_job_id,
        filename=version.filename or document.filename,
        mime=document.mime,
        original="missing",
        missing_reason="original_unavailable",
        uploader_ref=resource.uploaded_by,
        policy_revision=f"{resource.publication}:{resource.updated_at.isoformat()}",
    )
    files = {}
    if document.object_key and await storage.exists(document.object_key):
        files["source.bin"] = await _get_bytes(storage, document.object_key)
        source.update(original="present", missing_reason=None)
    layout = {
        "schema": "ddp-bundle-layout/1",
        "state": "missing",
        "layout": None,
        "reason": "parse_revision_unbound",
    }
    records = []
    if version.parse_job_id:
        job = await session.get(ParseJob, version.parse_job_id)
        if job is None or job.document_id != document.id:
            raise APIError(
                409,
                "parse revision does not belong to version",
                "server_error",
                "bundle_binding_invalid",
            )
        layout["reason"] = "layout_unavailable"
        layout_key = prefix_of(job) + "layout.json"
        if await storage.exists(layout_key):
            layout.update(
                state="present",
                layout=parse_json(await _get_bytes(storage, layout_key)),
                reason=None,
            )
        rows = list(
            (
                await session.execute(
                    select(Evidence)
                    .where(Evidence.document_id == document.id, Evidence.parse_job_id == job.id)
                    .order_by(Evidence.seq, Evidence.id)
                )
            ).scalars()
        )
        for evidence in rows:
            page = evidence.page_size
            size = (
                {"width": page[0], "height": page[1]}
                if isinstance(page, list) and len(page) == 2
                else page
                if isinstance(page, dict)
                else None
            )
            envelope = dict(
                schema="ddp-evidence/1#FederatedEvidence",
                evidence_id=evidence.id,
                **{key: source[key] for key in IDENTITY},
                excerpt_digest=digest(evidence.content.encode()),
                locator={
                    "kind": "page_block",
                    "physical_page_index": evidence.page_idx,
                    "seq": evidence.seq,
                    "bbox": evidence.bbox,
                    "page_size": size,
                },
                source_type="generated" if evidence.derived_from else "source",
                derived_from=evidence.derived_from,
                uploader_ref=source["uploader_ref"],
                retrieval_receipt_ref=None,
                policy_revision=source["policy_revision"],
                block_type=evidence.kind,
            )
            records.append({"evidence": envelope, "excerpt": evidence.content})
    files["layout.json"] = json_bytes(layout)
    files["evidence.json"] = json_bytes(records)
    files["provenance.json"] = json_bytes(
        [{"activity": "export", "source": source, "legacy_document_id": document.id}]
    )
    # Native layout bbox transform metadata travels inside `layout.json` bytes and
    # is never re-derived here: the fixed layout round-trips verbatim.
    return read_bundle(io.BytesIO(build_bundle(source, files)))


async def _wiki_payload(session, resource, version, *, source, evidence_digests) -> dict | None:
    # Exported Wiki is a draft snapshot of the newest local revision that cites
    # this version: human paragraphs verbatim, generated claims with their fixed
    # evidence bindings. No auto-publish: the importer must mint a fresh local
    # revision (new dependency manifest) before publishing derived content.
    # External bindings keep their original source identity verbatim and stay
    # needs_review: a qualified source:+hash ref is never resolved through the
    # local evidence FK and never marked available.
    from ddp_corpus.models import DependencyManifest, WikiPage, WikiRevision

    candidates = list(
        (
            await session.execute(
                select(DependencyManifest)
                .where(
                    DependencyManifest.resource_id == resource.id,
                    DependencyManifest.source_version_id == version.id,
                )
                .order_by(DependencyManifest.revision_id)
            )
        ).scalars()
    )
    if not candidates:
        return None
    revision_id = candidates[-1].revision_id
    revision = await session.get(WikiRevision, revision_id)
    pages = list(
        (
            await session.execute(
                select(WikiPage)
                .where(WikiPage.revision_id == revision_id)
                .order_by(WikiPage.position, WikiPage.page_key)
            )
        ).scalars()
    )
    if not pages or len(pages) > 50:
        return None
    page_keys = {page.page_key for page in pages}
    if any(not page.page_key or len(page.page_key) > 64 for page in pages):
        return None
    title = revision.title if revision is not None else None
    if title is not None and (not title or len(title) > 255):
        return None
    manifest_rows = [c for c in candidates if c.revision_id == revision_id]
    # Local identity for this bundle: external rows keep their own source.
    local_source = {key: source[key] for key in IDENTITY}
    deps: list[dict] = []
    valid_ids: set[str] = set()
    seen_bindings: set[tuple[str, str]] = set()
    for dep in manifest_rows:
        page_key = dep.page_key
        if page_key not in page_keys:
            continue
        evidence_id = dep.evidence_id
        if not evidence_id or len(evidence_id) > 128:
            continue
        if (page_key, evidence_id) in seen_bindings:
            continue
        excerpt = dep.excerpt_digest or ""
        excerpt_digest = excerpt if excerpt.startswith("sha256:") else "sha256:" + excerpt
        if len(excerpt_digest) != 71:
            continue
        origin = dep.origin_node_id
        if not origin:
            # Local binding: must resolve to bundled evidence bytes.
            if evidence_id not in evidence_digests:
                continue
            if evidence_digests[evidence_id] != excerpt_digest:
                continue
            deps.append(
                {
                    "page_key": page_key,
                    "evidence_id": evidence_id,
                    "excerpt_digest": excerpt_digest,
                    "source": dict(local_source),
                    "review": "available",
                }
            )
            seen_bindings.add((page_key, evidence_id))
            valid_ids.add(evidence_id)
            continue
        # External binding: never relabeled as local evidence, never available.
        if evidence_id in evidence_digests:
            return None
        dep_source_digest = dep.source_digest or ""
        dep_source_digest = (
            dep_source_digest if dep_source_digest.startswith("sha256:") else "sha256:" + dep_source_digest
        )
        if len(dep_source_digest) != 71:
            continue
        dep_source = {
            "origin_node_id": dep.origin_node_id,
            "authority_node_id": dep.authority_node_id or dep.origin_node_id,
            "resource_id": dep.resource_id,
            "source_version_id": dep.source_version_id,
            "source_digest": dep_source_digest,
            "parse_revision": dep.parse_revision,
        }
        if any(not isinstance(value, str) or not value for value in dep_source.values()):
            continue
        entry: dict = {
            "page_key": page_key,
            "evidence_id": evidence_id,
            "excerpt_digest": excerpt_digest,
            "source": dep_source,
            "review": "needs_review",
        }
        if dep.source_evidence_id and len(dep.source_evidence_id) <= 128:
            entry["source_evidence_id"] = dep.source_evidence_id
        if dep.policy_revision and len(dep.policy_revision) <= 128:
            entry["policy_revision"] = dep.policy_revision
        # Stored locators use the local {page_idx,...} shape, not the bundle
        # {physical_page_index,seq,...} shape: omit rather than mistranslate.
        locator = dep.locator if isinstance(dep.locator, dict) else None
        if isinstance(locator, dict) and isinstance(locator.get("physical_page_index"), int):
            entry["locator"] = locator
        deps.append(entry)
        seen_bindings.add((page_key, evidence_id))
        valid_ids.add(evidence_id)
    if not deps:
        return None
    out_pages = []
    for page in pages:
        if not page.title or len(page.title) > 255:
            return None
        sections = []
        for section in page.generated_sections or []:
            if not isinstance(section, dict):
                return None
            heading = section.get("heading")
            if heading is not None and (not isinstance(heading, str) or len(heading) > 512):
                return None
            claims = []
            seen_claims: set[str] = set()
            for sentence in section.get("sentences") or section.get("claims") or []:
                if not isinstance(sentence, dict):
                    return None
                claim_id = sentence.get("id") or sentence.get("claim_id") or ""
                text = sentence.get("text") or ""
                if not claim_id or len(claim_id) > 64 or claim_id in seen_claims:
                    return None
                seen_claims.add(claim_id)
                if not text or len(text) > 10000:
                    return None
                kept = [eid for eid in (sentence.get("evidence_ids") or []) if eid in valid_ids]
                unsupported = bool(sentence.get("unsupported", not bool(sentence.get("evidence_ids"))))
                if not kept:
                    unsupported = True
                claim: dict = {
                    "claim_id": claim_id,
                    "text": text,
                    "evidence_ids": kept,
                    "unsupported": unsupported,
                }
                conflict = sentence.get("conflict_group")
                if conflict is not None:
                    if not isinstance(conflict, str) or not conflict or len(conflict) > 512:
                        return None
                    claim["conflict_group"] = conflict
                claims.append(claim)
            if len(claims) > 100:
                return None
            sections.append({"heading": heading, "claims": claims})
        if len(sections) > 50:
            return None
        paragraphs = []
        seen_paragraphs: set[str] = set()
        for paragraph in page.human_paragraphs or []:
            if not isinstance(paragraph, dict):
                return None
            pid, ptext = paragraph.get("id"), paragraph.get("text")
            if not pid or len(pid) > 64 or pid in seen_paragraphs:
                return None
            seen_paragraphs.add(pid)
            if not isinstance(ptext, str) or not ptext or len(ptext) > 10000:
                return None
            paragraphs.append({"id": pid, "text": ptext})
        if len(paragraphs) > 100:
            return None
        out_pages.append(
            {
                "page_key": page.page_key,
                "title": page.title,
                "generated_sections": sections,
                "human_paragraphs": paragraphs,
            }
        )
    if not out_pages:
        return None
    relations: list[dict] = []
    stored_relations = list(getattr(revision, "relations", None) or []) if revision is not None else []
    if len(stored_relations) > 50:
        return None
    for relation in stored_relations:
        if not isinstance(relation, dict):
            return None
        subject = relation.get("subject_page", relation.get("subject_id"))
        obj = relation.get("object_page", relation.get("object_id"))
        predicate = relation.get("predicate")
        evidence_ids = relation.get("evidence_ids") or []
        if (
            not subject
            or not obj
            or subject == obj
            or subject not in page_keys
            or obj not in page_keys
            or not isinstance(predicate, str)
            or not predicate.strip()
            or len(predicate) > 255
            or not isinstance(evidence_ids, list)
            or any(eid not in valid_ids for eid in evidence_ids)
        ):
            continue
        relations.append(
            {
                "subject_page": subject,
                "object_page": obj,
                "predicate": predicate,
                "evidence_ids": list(evidence_ids),
                "unsupported": bool(relation.get("unsupported", not bool(evidence_ids))),
            }
        )
    return {
        "schema": "ddp-bundle-wiki/1",
        "state": "draft",
        "title": title,
        "pages": out_pages,
        "reason": None,
        "relations": relations,
        "dependency_manifest": deps,
    }
async def _vectors_payload(session, storage, resource, version, job, chunks) -> dict:
    # Vectors record their full compatibility identity (model/version/dimension/
    # chunking/source-evidence) so the consumer rebuilds on mismatch instead of
    # trusting bytes. Missing vectors are an explicit statement, not an omission:
    # the `missing` branch carries null identity per the bundle validator.
    # Model version is the observed provider fingerprint (never invented from the
    # model name); tokenizer/chunker/max_chars equal the running configuration,
    # and rows only cover chunk text that matches the bundled evidence digests.
    from ddp_core.compilation import CHUNKER_VERSION
    from ddp_core.tokenize import backend as tokenizer_backend
    from ddp_corpus.config import settings as corpus_settings

    def _missing(reason: str) -> dict:
        return {
            "schema": "ddp-bundle-vectors/1",
            "state": "missing",
            "model": None,
            "dimension": None,
            "preprocessing": None,
            "chunking": None,
            "format": None,
            "source": None,
            "vectors": [],
            "reason": reason,
        }

    if job is None or version.parse_job_id is None:
        return _missing("parse_revision_unbound")
    model_name = (corpus_settings.embedding_model or "").strip()
    if not model_name:
        return _missing("model_unresolved")
    candidates = [c for c in (chunks or []) if c.embedding is not None]
    if not candidates:
        return _missing("vectors_not_indexed")
    dimension = corpus_settings.embedding_dim
    for chunk in candidates:
        embedding = list(chunk.embedding)
        if len(embedding) != dimension:
            return _missing("dimension_mismatch")
        provider = chunk.provider or {}
        observed_model = provider.get("embedding_model")
        if observed_model and observed_model != model_name:
            return _missing("model_mismatch")
    fingerprints = {(chunk.provider_fingerprint or "") for chunk in candidates}
    if len(fingerprints) != 1 or not next(iter(fingerprints)):
        return _missing("version_unresolved")
    model_version = next(iter(fingerprints))
    if model_version == model_name:
        return _missing("version_unresolved")
    tokenizer = tokenizer_backend()
    max_chars = corpus_settings.chunk_max_chars
    rows = []
    for chunk in candidates:
        rows.append(
            {
                "evidence_id": chunk.evidence_id or chunk.id,
                "excerpt_digest": digest((chunk.text or "").encode()),
                "embedding": list(chunk.embedding),
            }
        )
    return {
        "schema": "ddp-bundle-vectors/1",
        "state": "present",
        "model": {"name": model_name, "version": model_version, "dimension": dimension},
        "dimension": dimension,
        "preprocessing": {"tokenizer": tokenizer, "normalization": "none"},
        "chunking": {"max_chars": max_chars, "tokenizer": tokenizer, "chunker": CHUNKER_VERSION},
        "format": {"dtype": "float32", "encoding": "json-list"},
        "source": {
            "source_digest": "sha256:" + version.source_digest,
            "parse_revision": version.parse_job_id,
            "evidence_count": len(rows),
        },
        "vectors": rows,
        "reason": None,
    }


@router.get("/api/resources/{resource_id}/versions/{version_id}/bundle")
async def export_bundle(
    resource_id: str,
    version_id: str,
    actor: Actor = Depends(current_actor),
    session: AsyncSession = Depends(get_session),
    storage=Depends(get_storage),
    include_wiki: bool = False,
    include_vectors: bool = False,
    licence_valid_until: str | None = None,
):
    resource, version = await _version(session, actor, resource_id, version_id)
    from ddp_corpus.bundle_source import licensed_version

    snapshot = await licensed_version(session, version)
    if snapshot is not None and snapshot.id != version.id:
        # A local reparse of a licensed copy would otherwise leave as a native source
        # under this node's identity with a fresh, holder-chosen term.
        raise APIError(409, "a reparse of a licensed copy cannot be exported as a new source; "
                       "export the imported snapshot version", "invalid_request_error",
                       "bundle_licensed_derivative")
    if version.bundle_prefix and licence_valid_until is not None:
        raise APIError(400, "only the source exporter may set the licence term",
                       "invalid_request_error", "bundle_licence_term_invalid")
    try:
        term = parse_licence_valid_until(licence_valid_until)
    except BundleError as exc:
        raise APIError(400, str(exc), "invalid_request_error", "bundle_licence_term_invalid") from exc
    if version.bundle_prefix:
        from ddp_corpus.bundle_source import licensed_source_binding

        await licensed_source_binding(session, storage, resource, version)
    try:
        bundle = await _snapshot(session, storage, resource, version)
        files = dict(bundle.files)
        source = dict(bundle.source)
        if term is not None:
            source["licence_valid_until"] = term.isoformat()
        features: list[str] = []
        if include_wiki:
            # Opt-in wiki stays off by default so private Wiki never leaks into
            # a plain export; when requested the identical ACL/source/version
            # facts travel (ACL, model, version, dimension, chunking, evidence).
            digests = {
                record["evidence"]["evidence_id"]: record["evidence"]["excerpt_digest"]
                for record in bundle.evidence
            }
            wiki = await _wiki_payload(
                session, resource, version, source=bundle.source, evidence_digests=digests
            )
            if wiki is not None:
                files["wiki.json"] = json_bytes(wiki)
                features.append("wiki")
        if include_vectors:
            job = None
            chunks: list = []
            if version.parse_job_id:
                maybe_job = await session.get(ParseJob, version.parse_job_id)
                document = await session.get(Document, version.document_id)
                if (
                    maybe_job is not None
                    and document is not None
                    and maybe_job.document_id == document.id
                ):
                    job = maybe_job
                    chunks = list(
                        (
                            await session.execute(
                                select(Chunk)
                                .where(Chunk.parse_job_id == job.id)
                                .order_by(Chunk.seq, Chunk.id)
                            )
                        ).scalars()
                    )
            vectors = await _vectors_payload(
                session, storage, resource, version, job, chunks
            )
            files["vectors.json"] = json_bytes(vectors)
            features.append("vectors")
        data = await asyncio.to_thread(
            build_bundle, source, files, required_features=features
        )
    except BundleError as exc:
        raise _bundle_error(exc) from exc
    # Recheck after storage reads. Permission changes during an export must not bypass ACL.
    await session.refresh(resource)
    await _version(session, actor, resource_id, version_id)
    if version.bundle_prefix:
        await licensed_source_binding(session, storage, resource, version)
    return Response(
        data,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="resource-{version.id}.ddp.zip"',
            "Cache-Control": "private, no-store",
        },
    )


@router.get("/api/resources/{resource_id}/versions/{version_id}/bundle/evidence")
async def bundle_evidence(
    resource_id: str,
    version_id: str,
    actor: Actor = Depends(current_actor),
    session: AsyncSession = Depends(get_session),
    storage=Depends(get_storage),
):
    resource, version = await _version(session, actor, resource_id, version_id)
    try:
        bundle = await _snapshot(session, storage, resource, version)
    except BundleError as exc:
        raise _bundle_error(exc) from exc
    await session.refresh(resource)
    await _version(session, actor, resource_id, version_id)
    return JSONResponse(
        {
            "source": bundle.source,
            "evidence": bundle.evidence,
            "structural_validation": "passed",
            "semantic_review": "needs_review",
        },
        headers={"Cache-Control": "private, no-store"},
    )


def _result(resource, version, source):
    return {
        "resource_id": resource.id,
        "source_version_id": version.id,
        "document_id": version.document_id,
        "source": source,
        "state": "ready",
        "index_state": "rebuild_required",
        "publication": resource.publication,
    }


async def _prior(session, actor, key, request_digest):
    prior = await session.scalar(
        select(UploadEvent).where(
            UploadEvent.actor_id == actor.principal_id, UploadEvent.idempotency_key == key
        )
    )
    if prior is None:
        return None
    if prior.request_digest != request_digest:
        raise APIError(
            409,
            "idempotency key already used with different bundle",
            "invalid_request_error",
            "idempotency_conflict",
        )
    version = await session.get(ResourceVersion, prior.resource_version_id)
    resource = await require_resource(session, actor, version.resource_id, write=True)
    if version.deleted_at is not None:
        raise APIError(
            409, "previous import was deleted", "invalid_request_error", "resource_deleted"
        )
    return resource, version


@router.post("/api/bundles/import")
async def import_bundle(
    request: Request,
    idempotency_key: str = Header(min_length=1, max_length=128),
    actor: Actor = Depends(current_actor),
    session: AsyncSession = Depends(get_session),
    storage=Depends(get_storage),
):
    actor.require(actor.can_upload and actor.principal_id is not None, "导入资源")
    if request.headers.get("content-type", "").split(";", 1)[0] != "application/zip":
        raise APIError(
            415, "expected application/zip", "invalid_request_error", "bundle_content_type"
        )
    hasher = hashlib.sha256()
    total = 0
    with SpooledTemporaryFile(max_size=1024 * 1024, mode="w+b") as staged:
        async for chunk in request.stream():
            total += len(chunk)
            if total > MAX_ARCHIVE:
                raise APIError(
                    413, "bundle exceeds upload limit", "invalid_request_error", "bundle_too_large"
                )
            hasher.update(chunk)
            staged.write(chunk)
        try:
            verified = await asyncio.to_thread(read_bundle, staged)
        except BundleError as exc:
            raise _bundle_error(exc) from exc
    if verified.source["original"] == "missing":
        return JSONResponse(
            {
                "state": "source_missing",
                "source": verified.source,
                "error": {
                    "type": "invalid_request_error",
                    "code": "bundle_source_missing",
                    "message": "supply the original bytes before importing a usable resource",
                },
            },
            status_code=409,
        )

    # Org-scoped operation key; no collision with upload event keys or another organization.
    key = (
        "bundle:"
        + hashlib.sha256((actor.organization_id + "\x00" + idempotency_key).encode()).hexdigest()
    )
    request_digest = hasher.hexdigest()
    prior = await _prior(session, actor, key, request_digest)
    if prior:
        return _result(*prior, verified.source)

    resource_id, version_id = new_id(), new_id()
    prefix = f"bundles/{version_id}/"
    written = []
    try:
        objects = {**verified.files, "manifest.json": json_bytes(verified.manifest)}
        for name, content in objects.items():
            object_key = prefix + name
            # Register cleanup before put: a backend can write bytes and then fail.
            written.append(object_key)
            await storage.put(
                object_key,
                content,
                verified.source["mime"] if name == "source.bin" else "application/json",
            )
            if digest(await _get_bytes(storage, object_key, len(content))) != digest(content):
                raise APIError(
                    502,
                    "stored bundle failed digest verification",
                    "server_error",
                    "bundle_storage_mismatch",
                )

        # Reuse content only after supplied bytes have been verified. Imported layouts and
        # evidence stay in the version snapshot and cannot overwrite an existing parse/index.
        document = await session.scalar(
            select(Document)
            .where(
                Document.doc_id == verified.source["source_digest"][7:], Document.origin == "bundle"
            )
            .with_for_update()
        )
        if document is None:
            document = Document(
                id=new_id(),
                organization_id=actor.organization_id,
                uploaded_by=actor.principal_id,
                doc_id=verified.source["source_digest"][7:],
                origin="bundle",
                filename=verified.source["filename"],
                mime=verified.source["mime"],
                size_bytes=len(verified.files["source.bin"]),
                object_key=prefix + "source.bin",
            )
            session.add(document)
            await session.flush()
        elif document.deleted_at is not None or not document.object_key:
            document.deleted_at = None
            document.object_key = prefix + "source.bin"
        resource = Resource(
            id=resource_id,
            organization_id=actor.organization_id,
            owner_id=actor.principal_id,
            uploaded_by=actor.principal_id,
            display_name=verified.source["filename"],
            publication="private",
            # A remote raw ID must never resolve to a published local ancestor.
            # The full source tuple stays in the manifest; publication remains closed
            # until its remote permission dependency can be resolved by a trusted grant.
            copied_from="remote:"
            + hashlib.sha256(
                json_bytes(
                    [
                        verified.source["origin_node_id"],
                        verified.source["authority_node_id"],
                        verified.source["resource_id"],
                    ]
                )
            ).hexdigest()[:25],
        )
        session.add(resource)
        await session.flush()
        version = ResourceVersion(
            id=version_id,
            resource_id=resource.id,
            document_id=document.id,
            version_no=1,
            source_digest=verified.source["source_digest"][7:],
            filename=verified.source["filename"],
            size_bytes=len(verified.files["source.bin"]),
            parse_job_id=None,
            bundle_prefix=prefix,
        )
        session.add(version)
        await session.flush()
        # Real materialization: the frozen snapshot becomes a searchable local
        # asset in the same transaction. The bundle layout is archived verbatim
        # under this version's own ParseJob; Evidence/Chunk rows are minted with
        # new local ids (never the foreign evidence ids); FTS text is indexed
        # on Chunk (including text_tokenized) and dense vectors stay explicit:
        # reused only on strict identity match, otherwise the real rebuild
        # chain owns them and nothing is marked ready.
        from ddp_core.anchor import digest_of
        from ddp_core.chunking import layout_to_chunks
        from ddp_core.compilation import fingerprint as _compile_fingerprint
        from ddp_core.compilation import (
            code_detection_of as _code_detection_of,
        )
        from ddp_core.compilation import (
            provider_of as _provider_of,
        )
        from ddp_core.tokenize import backend as _tokenizer_backend
        from ddp_core.tokenize import code_tokenized as _code_tokenized
        from ddp_core.tokenize import tokenized as _tokenized
        from ddp_corpus.bundle_models import BundleReplica
        from ddp_corpus.ingest import options_hash as _options_hash
        from ddp_corpus.versions import next_document_version

        layout_payload = parse_json(verified.files["layout.json"])
        layout_state = layout_payload.get("state")
        layout_body = layout_payload.get("layout")
        job = ParseJob(
            document_id=document.id,
            engine="bundle",
            options={
                "bundle_import": True,
                "origin_node_id": verified.source["origin_node_id"],
                "authority_node_id": verified.source["authority_node_id"],
                "source_resource_id": verified.source["resource_id"],
                "source_version_id": verified.source["source_version_id"],
            },
            initiated_by=actor.principal_id,
            resource_id=resource.id,
            options_hash=_options_hash("bundle", {"bundle": "import/1"}),
            document_version=await next_document_version(session, document.id),
            status="succeeded",
            error=None,
            page_count=len((layout_body or {}).get("pdf_info") or []),
            result_prefix=f"results/bundle-{version_id}/",
        )
        session.add(job)
        await session.flush()
        version.parse_job_id = job.id
        await session.flush()
        await storage.put(
            f"{job.result_prefix}layout.json",
            json_bytes(layout_body if isinstance(layout_body, dict) else {}),
            "application/json",
        )
        written.append(f"{job.result_prefix}layout.json")
        if layout_state != "present" or not isinstance(layout_body, dict):
            job.compile_status = "failed"
            job.compile_degraded = ["layout_unavailable"]
            job.index_status = "failed"
            job.index_error = layout_payload.get("reason") or "layout_unavailable"
            job.index_generation = 0
        else:
            frozen_provider = _provider_of(
                layout=layout_body,
                parse_options_hash=job.options_hash,
                embedding_model=settings.embedding_model,
                vision_model=settings.chat_model,
            )
            frozen_fingerprint = _compile_fingerprint(frozen_provider)
            id_by_bundle: dict[str, Evidence] = {}
            for record in verified.evidence:
                envelope = record["evidence"]
                locator = envelope.get("locator") or {}
                size = locator.get("page_size") or {}
                row = Evidence(
                    document_id=document.id,
                    doc_version=job.document_version,
                    parse_job_id=job.id,
                    seq=int(locator.get("seq") or 0),
                    atom_key=f"bundle:{envelope['evidence_id']}",
                    page_idx=int(locator.get("physical_page_index") or 0),
                    bbox=locator.get("bbox"),
                    page_size=[size.get("width"), size.get("height")]
                    if isinstance(size, dict) and size.get("width") and size.get("height")
                    else None,
                    kind=envelope.get("block_type") or "text",
                    content_digest=digest_of(record["excerpt"]),
                    content=record["excerpt"],
                    provider=dict(frozen_provider),
                    provider_fingerprint=frozen_fingerprint,
                )
                session.add(row)
                await session.flush()
                id_by_bundle[envelope["evidence_id"]] = row
            # Generated excerpts point at their bundled source parent, already
            # validated acyclic by the bundle parser.
            for record in verified.evidence:
                envelope = record["evidence"]
                if envelope.get("source_type") != "generated" or not envelope.get("derived_from"):
                    continue
                child = id_by_bundle[envelope["evidence_id"]]
                parent = id_by_bundle.get(envelope["derived_from"])
                if parent is not None:
                    child.derived_from = parent.id
            by_seq: dict[int, Evidence] = {}
            for row in id_by_bundle.values():
                by_seq.setdefault(row.seq, row)
            expected_chunks = layout_to_chunks(layout_body, settings.chunk_max_chars)
            compatible = (
                verified.vectors is not None
                and verified.vectors.get("state") == "present"
                and verified.vectors.get("dimension") == settings.embedding_dim
                and isinstance(verified.vectors.get("model"), dict)
                and verified.vectors["model"].get("name") == (settings.embedding_model or "").strip()
                and settings.embedding_model.strip()
                and verified.vectors["model"].get("version") == frozen_fingerprint
                and verified.vectors["model"].get("version") != verified.vectors["model"].get("name")
                and isinstance(verified.vectors.get("preprocessing"), dict)
                and verified.vectors["preprocessing"].get("tokenizer") == _tokenizer_backend()
                and isinstance(verified.vectors.get("chunking"), dict)
                and verified.vectors["chunking"].get("max_chars") == settings.chunk_max_chars
                and verified.vectors["chunking"].get("tokenizer") == _tokenizer_backend()
                and isinstance(verified.vectors.get("source"), dict)
                and verified.vectors["source"].get("source_digest") == verified.source["source_digest"]
                and verified.vectors["source"].get("parse_revision")
                == verified.source["parse_revision"]
                and verified.vectors["source"].get("evidence_count") == len(verified.vectors.get("vectors") or [])
            )
            bundled_vectors: dict[str, list[float]] = {}
            bundled_digests: dict[str, str] = {}
            if compatible:
                for entry in verified.vectors["vectors"]:
                    bundled_vectors[entry["evidence_id"]] = list(entry["embedding"])
                    bundled_digests[entry["evidence_id"]] = entry["excerpt_digest"]
            chunk_rows: list[Chunk] = []
            for index, bundle_chunk in enumerate(expected_chunks):
                excerpt = "\n".join(
                    [
                        record["excerpt"]
                        for record in verified.evidence
                        if int((record["evidence"].get("locator") or {}).get("seq") or 0)
                        == bundle_chunk["seq"]
                    ]
                ) or bundle_chunk.get("text") or ""
                bound = [row for row in id_by_bundle.values() if row.seq == bundle_chunk["seq"]]
                primary = min(bound, key=lambda row: row.id) if bound else by_seq.get(index)
                if primary is None:
                    primary = Evidence(
                        document_id=document.id,
                        doc_version=job.document_version,
                        parse_job_id=job.id,
                        seq=bundle_chunk["seq"],
                        atom_key=f"bundle:chunk:{bundle_chunk['seq']}",
                        page_idx=bundle_chunk.get("page_idx") or 0,
                        bbox=bundle_chunk.get("bbox"),
                        page_size=bundle_chunk.get("page_size"),
                        kind=bundle_chunk.get("block_type") or "text",
                        content_digest=digest_of(excerpt),
                        content=excerpt,
                        provider=dict(frozen_provider),
                        provider_fingerprint=frozen_fingerprint,
                    )
                    session.add(primary)
                    await session.flush()
                text_tokenized = (
                    _code_tokenized(excerpt)
                    if (bundle_chunk.get("block_type") or "text") == "code"
                    else _tokenized(excerpt)
                )
                row_digest = digest(excerpt.encode())
                vector = bundled_vectors.get(
                    next(
                        (
                            envelope["evidence_id"]
                            for envelope in (
                                record["evidence"] for record in verified.evidence
                            )
                            if envelope.get("excerpt_digest") == row_digest
                            and bundled_digests.get(envelope["evidence_id"]) == row_digest
                        ),
                        "",
                    )
                )
                if vector is not None and len(vector) != settings.embedding_dim:
                    vector = None
                chunk_rows.append(
                    Chunk(
                        document_id=document.id,
                        parse_job_id=job.id,
                        seq=bundle_chunk["seq"],
                        page_idx=bundle_chunk.get("page_idx") or 0,
                        bbox=bundle_chunk.get("bbox"),
                        page_size=bundle_chunk.get("page_size"),
                        text=excerpt,
                        search_text=excerpt,
                        derived_text=None,
                        char_len=len(excerpt),
                        block_type=bundle_chunk.get("block_type") or "text",
                        table_html=bundle_chunk.get("table_html"),
                        text_tokenized=text_tokenized,
                        provider=dict(frozen_provider),
                        provider_fingerprint=frozen_fingerprint,
                        evidence_id=primary.id,
                        derived_evidence_id=None,
                        embedding=vector,
                    )
                )
            if chunk_rows:
                session.add_all(chunk_rows)
                await session.flush()
            job.compile_status = "ready"
            job.compile_degraded = []
            job.compile_fingerprint = frozen_fingerprint
            job.layout_version = str(layout_body.get("layout_version") or "")
            job.code_detection = _code_detection_of(layout_body)
            if not chunk_rows:
                job.index_status = "failed"
                job.index_error = "no_compiled_chunks"
            elif not compatible and verified.vectors is not None:
                # Explicitly incompatible bundled vectors: the real rebuild
                # chain owns dense vectors; never mark them ready from bytes.
                job.index_status = "pending"
                job.index_error = "vectors_incompatible_rebuild_required"
            elif any(row.embedding is None for row in chunk_rows):
                job.index_status = "pending"
                job.index_error = "vectors_rebuild_required"
            else:
                job.index_status = "ready"
                job.index_error = None
            from ddp_corpus import queue as _bundle_queue

            await _bundle_queue.enqueue(
                session,
                kind="index",
                payload={
                    "document_id": document.id,
                    "job_id": job.id,
                    "resource_version_id": version.id,
                },
                organization_id=actor.organization_id,
                dedupe_key=f"index:{job.id}",
            )
        # Licensed-copy ledger: this import is already owned by the caller, so
        # record the fixed local version/digest it snapshots. Reads reuse the
        # fixed version authorization plus these bytes, never a new permission.
        session.add(
            BundleReplica(
                organization_id=actor.organization_id,
                resource_id=resource.id,
                source_version_id=version.id,
                document_id=document.id,
                owner_id=resource.owner_id,
                created_by=actor.principal_id,
                origin_node_id=verified.source["origin_node_id"],
                authority_node_id=verified.source["authority_node_id"],
                source_digest=verified.source["source_digest"][7:],
                policy_revision=verified.source["policy_revision"],
                valid_until=parse_licence_valid_until(verified.source.get("licence_valid_until")),
            )
        )
        await session.flush()
        wiki_payload = verified.wiki
        if wiki_payload is not None and wiki_payload.get("state") == "draft":
            id_by_bundle = {
                record["evidence"]["evidence_id"]: record for record in verified.evidence
            }
            local_by_bundle = {
                row.atom_key.split("bundle:", 1)[1]: row
                for row in (
                    await session.execute(
                        select(Evidence).where(Evidence.parse_job_id == job.id)
                    )
                ).scalars()
                if row.atom_key.startswith("bundle:")
            }
            import hashlib as _hashlib

            def _ref(envelope: dict) -> str:
                raw = json_bytes(
                    [
                        envelope.get("origin_node_id"),
                        envelope.get("resource_id"),
                        envelope.get("source_version_id"),
                        envelope.get("parse_revision"),
                        envelope.get("evidence_id"),
                    ]
                )
                return "source:+" + _hashlib.sha256(raw).hexdigest()

            remapped: dict[str, str] = {}
            local_deps: list[dict] = []
            for dep in wiki_payload.get("dependency_manifest") or []:
                bundle_id = dep.get("evidence_id")
                record = id_by_bundle.get(bundle_id)
                if record is None:
                    continue
                envelope = record["evidence"]
                local_row = local_by_bundle.get(bundle_id)
                if local_row is None:
                    continue
                ref = _ref(envelope)
                remapped[bundle_id] = ref
                local_deps.append(
                    {
                        "page_key": dep.get("page_key"),
                        "resource_id": resource.id,
                        "source_version_id": version.id,
                        "document_id": document.id,
                        "source_digest": version.source_digest,
                        "parse_revision": job.id,
                        "evidence_id": ref,
                        "source_evidence_id": local_row.id,
                        "excerpt_digest": local_row.content_digest,
                        "locator": {
                            "page_idx": local_row.page_idx,
                            "bbox": local_row.bbox,
                            "page_size": local_row.page_size,
                            "kind": local_row.kind,
                        },
                        "origin_node_id": envelope.get("origin_node_id"),
                        "authority_node_id": envelope.get("authority_node_id"),
                        "source_publication": "private",
                        "policy_revision": verified.source["policy_revision"],
                        "derivative_grant": None,
                        "retrieval_receipt_ref": None,
                    }
                )
            external_deps: list[dict] = []
            for dep in wiki_payload.get("dependency_manifest") or []:
                bundle_id = dep.get("evidence_id")
                if bundle_id in remapped or bundle_id in id_by_bundle:
                    continue
                dep_source = dep.get("source") if isinstance(dep.get("source"), dict) else {}
                external_id = f"source:+{_hashlib.sha256(json_bytes([dep_source.get('origin_node_id'), dep_source.get('resource_id'), dep_source.get('source_version_id'), dep_source.get('parse_revision'), bundle_id])).hexdigest()}"
                remapped[bundle_id] = external_id
                external_deps.append(
                    {
                        "page_key": dep.get("page_key"),
                        "resource_id": resource.id,
                        "source_version_id": version.id,
                        "document_id": document.id,
                        "source_digest": version.source_digest,
                        "parse_revision": job.id,
                        "evidence_id": external_id,
                        "source_evidence_id": bundle_id,
                        "excerpt_digest": (dep.get("excerpt_digest") or "")[7:],
                        "locator": dep.get("locator") if isinstance(dep.get("locator"), dict) else {},
                        "origin_node_id": dep_source.get("origin_node_id"),
                        "authority_node_id": dep_source.get("authority_node_id"),
                        "source_publication": "private",
                        "policy_revision": dep.get("policy_revision")
                        or verified.source["policy_revision"],
                        "derivative_grant": None,
                        "retrieval_receipt_ref": None,
                    }
                )
            if local_deps or external_deps:
                pages: list[dict] = []
                for page in wiki_payload.get("pages") or []:
                    sections = []
                    for section in page.get("generated_sections") or []:
                        sentences = []
                        for claim in section.get("claims") or []:
                            sentences.append(
                                {
                                    "id": claim.get("claim_id"),
                                    "text": claim.get("text"),
                                    "evidence_ids": [
                                        remapped.get(eid, eid)
                                        for eid in (claim.get("evidence_ids") or [])
                                    ],
                                    "unsupported": claim.get("unsupported", False),
                                    **(
                                        {"conflict_group": claim.get("conflict_group")}
                                        if claim.get("conflict_group") is not None
                                        else {}
                                    ),
                                }
                            )
                        sections.append(
                            {"heading": section.get("heading"), "sentences": sentences}
                        )
                    pages.append(
                        {
                            "page_key": page.get("page_key"),
                            "title": page.get("title"),
                            "generated_sections": sections,
                            "human_paragraphs": list(page.get("human_paragraphs") or []),
                        }
                    )
                from ddp_corpus.federated_wiki import import_bundle_wiki

                await import_bundle_wiki(
                    session,
                    actor,
                    wiki_id=None,
                    base_revision_id=None,
                    title=wiki_payload.get("title") or version.filename,
                    pages=pages,
                    deps=local_deps + external_deps,
                    provider={
                        "bundle_origin": verified.source["origin_node_id"],
                        "bundle_authority": verified.source["authority_node_id"],
                        "bundle_source_version": verified.source["source_version_id"],
                    },
                    limits={},
                    key=f"bundle:{version.id}",
                )
        if not await session.scalar(
            select(DocumentUpload.id).where(
                DocumentUpload.document_id == document.id,
                DocumentUpload.user_id == actor.principal_id,
            )
        ):
            session.add(DocumentUpload(document_id=document.id, user_id=actor.principal_id))
        session.add(
            UploadEvent(
                resource_version_id=version.id,
                actor_id=actor.principal_id,
                idempotency_key=key,
                request_digest=request_digest,
            )
        )
        await session.commit()
    except BaseException as exc:
        await session.rollback()
        for key_to_remove in written:
            try:
                await storage.delete(key_to_remove)
            except Exception:
                # An orphan is unreachable from any published version; never clean a
                # different import's prefix to compensate for a backend failure.
                pass
        if isinstance(exc, IntegrityError):
            prior = await _prior(session, actor, key, request_digest)
            if prior:
                return _result(*prior, verified.source)
            raise APIError(
                409,
                "concurrent import; retry with the same idempotency key",
                "invalid_request_error",
                "bundle_import_retry",
            ) from exc
        raise
    return JSONResponse(_result(resource, version, verified.source), status_code=201)
