"""Portable, authorized resource snapshots. See contracts/ddp/bundle-format.md."""

import asyncio
import hashlib
import io
from tempfile import SpooledTemporaryFile

from ddp_core.bundle import (
    IDENTITY,
    MAX_ARCHIVE,
    MAX_FILE,
    MAX_MANIFEST,
    NODE_ID,
    BundleError,
    VerifiedBundle,
    build_bundle,
    digest,
    json_bytes,
    parse_json,
    read_bundle,
    validate_parts,
)
from fastapi import APIRouter, Depends, Header, Request
from fastapi.responses import JSONResponse, Response
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from ddp_corpus import node_identity
from ddp_corpus.config import settings
from ddp_corpus.db import get_session
from ddp_corpus.deps import Actor, current_actor, get_storage
from ddp_corpus.errors import APIError
from ddp_corpus.models import (
    Document,
    DocumentUpload,
    Evidence,
    ParseJob,
    Resource,
    ResourceVersion,
    UploadEvent,
    new_id,
)
from ddp_corpus.policy import require_resource
from ddp_corpus.storage import prefix_of

router = APIRouter()


def _bundle_error(exc: BundleError) -> APIError:
    return APIError(
        413 if exc.code == "bundle_too_large" else 422, str(exc), "invalid_request_error", exc.code
    )


async def _version(session, actor, resource_id, version_id):
    resource = await require_resource(session, actor, resource_id)
    version = await session.scalar(
        select(ResourceVersion).where(
            ResourceVersion.id == version_id,
            ResourceVersion.resource_id == resource.id,
            ResourceVersion.deleted_at.is_(None),
        )
    )
    if version is None:
        raise APIError(
            404, "resource version not found", "invalid_request_error", "resource_not_found"
        )
    return resource, version


async def _get_bytes(storage, key: str, maximum: int = MAX_FILE) -> bytes:
    try:
        return await storage.get_limited(key, maximum)
    except ValueError as exc:
        raise BundleError("bundle_too_large", "stored object exceeds bundle limit") from exc


async def _snapshot(session, storage, resource, version) -> VerifiedBundle:
    if version.bundle_prefix:
        # Only prefixes generated by this service can be dereferenced. Manifest filenames
        # never become storage keys before validation.
        expected = f"bundles/{version.id}/"
        if version.bundle_prefix != expected:
            raise APIError(
                409, "invalid stored bundle binding", "server_error", "bundle_binding_invalid"
            )
        raw = await _get_bytes(storage, expected + "manifest.json", MAX_MANIFEST)
        manifest = parse_json(raw)
        if not isinstance(manifest, dict) or not isinstance(manifest.get("source"), dict):
            raise BundleError("bundle_invalid", "invalid stored bundle manifest")
        names = ["layout.json", "evidence.json", "provenance.json"]
        if manifest.get("source", {}).get("original") == "present":
            names.append("source.bin")
        files = {name: await _get_bytes(storage, expected + name) for name in names}
        return validate_parts(manifest, files)

    # Bundle 的来源身份取**唯一那个**节点身份（控制面密钥派生、启动时绑定），
    # 不再直接读 BUNDLE_NODE_ID：两个身份源不一致时导出的 Bundle 会声称自己
    # 出自一个谁也验不了的节点，而且不报错。
    node = node_identity.local_node_id()
    if not NODE_ID.fullmatch(node):
        raise APIError(
            503,
            "configure BUNDLE_NODE_ID to a persistent unique node identity",
            "server_error",
            "node_identity_unconfigured",
        )
    document = await session.get(Document, version.document_id)
    if document is None:
        raise APIError(409, "missing resource document", "server_error", "bundle_binding_invalid")
    source = dict(
        origin_node_id=node,
        authority_node_id=node,
        resource_id=resource.id,
        source_version_id=version.id,
        source_digest="sha256:" + version.source_digest,
        parse_revision=version.parse_job_id,
        filename=version.filename or document.filename,
        mime=document.mime,
        original="missing",
        missing_reason="original_unavailable",
        uploader_ref=resource.uploaded_by,
        policy_revision=f"{resource.publication}:{resource.updated_at.isoformat()}",
    )
    files = {}
    if document.object_key and await storage.exists(document.object_key):
        files["source.bin"] = await _get_bytes(storage, document.object_key)
        source.update(original="present", missing_reason=None)
    layout = {
        "schema": "ddp-bundle-layout/1",
        "state": "missing",
        "layout": None,
        "reason": "parse_revision_unbound",
    }
    records = []
    if version.parse_job_id:
        job = await session.get(ParseJob, version.parse_job_id)
        if job is None or job.document_id != document.id:
            raise APIError(
                409,
                "parse revision does not belong to version",
                "server_error",
                "bundle_binding_invalid",
            )
        layout["reason"] = "layout_unavailable"
        layout_key = prefix_of(job) + "layout.json"
        if await storage.exists(layout_key):
            layout.update(
                state="present",
                layout=parse_json(await _get_bytes(storage, layout_key)),
                reason=None,
            )
        rows = list(
            (
                await session.execute(
                    select(Evidence)
                    .where(Evidence.document_id == document.id, Evidence.parse_job_id == job.id)
                    .order_by(Evidence.seq, Evidence.id)
                )
            ).scalars()
        )
        for evidence in rows:
            page = evidence.page_size
            size = (
                {"width": page[0], "height": page[1]}
                if isinstance(page, list) and len(page) == 2
                else page
                if isinstance(page, dict)
                else None
            )
            envelope = dict(
                schema="ddp-evidence/1#FederatedEvidence",
                evidence_id=evidence.id,
                **{key: source[key] for key in IDENTITY},
                excerpt_digest=digest(evidence.content.encode()),
                locator={
                    "kind": "page_block",
                    "physical_page_index": evidence.page_idx,
                    "seq": evidence.seq,
                    "bbox": evidence.bbox,
                    "page_size": size,
                },
                source_type="generated" if evidence.derived_from else "source",
                derived_from=evidence.derived_from,
                uploader_ref=source["uploader_ref"],
                retrieval_receipt_ref=None,
                policy_revision=source["policy_revision"],
                block_type=evidence.kind,
            )
            records.append({"evidence": envelope, "excerpt": evidence.content})
    files["layout.json"] = json_bytes(layout)
    files["evidence.json"] = json_bytes(records)
    files["provenance.json"] = json_bytes(
        [{"activity": "export", "source": source, "legacy_document_id": document.id}]
    )
    return read_bundle(io.BytesIO(build_bundle(source, files)))


@router.get("/api/resources/{resource_id}/versions/{version_id}/bundle")
async def export_bundle(
    resource_id: str,
    version_id: str,
    actor: Actor = Depends(current_actor),
    session: AsyncSession = Depends(get_session),
    storage=Depends(get_storage),
):
    resource, version = await _version(session, actor, resource_id, version_id)
    try:
        bundle = await _snapshot(session, storage, resource, version)
        data = await asyncio.to_thread(build_bundle, bundle.source, bundle.files)
    except BundleError as exc:
        raise _bundle_error(exc) from exc
    # Recheck after storage reads. Permission changes during an export must not bypass ACL.
    await session.refresh(resource)
    await _version(session, actor, resource_id, version_id)
    return Response(
        data,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="resource-{version.id}.ddp.zip"',
            "Cache-Control": "private, no-store",
        },
    )


@router.get("/api/resources/{resource_id}/versions/{version_id}/bundle/evidence")
async def bundle_evidence(
    resource_id: str,
    version_id: str,
    actor: Actor = Depends(current_actor),
    session: AsyncSession = Depends(get_session),
    storage=Depends(get_storage),
):
    resource, version = await _version(session, actor, resource_id, version_id)
    try:
        bundle = await _snapshot(session, storage, resource, version)
    except BundleError as exc:
        raise _bundle_error(exc) from exc
    await session.refresh(resource)
    await _version(session, actor, resource_id, version_id)
    return JSONResponse(
        {
            "source": bundle.source,
            "evidence": bundle.evidence,
            "structural_validation": "passed",
            "semantic_review": "needs_review",
        },
        headers={"Cache-Control": "private, no-store"},
    )


def _result(resource, version, source):
    return {
        "resource_id": resource.id,
        "source_version_id": version.id,
        "document_id": version.document_id,
        "source": source,
        "state": "ready",
        "index_state": "rebuild_required",
        "publication": resource.publication,
    }


async def _prior(session, actor, key, request_digest):
    prior = await session.scalar(
        select(UploadEvent).where(
            UploadEvent.actor_id == actor.principal_id, UploadEvent.idempotency_key == key
        )
    )
    if prior is None:
        return None
    if prior.request_digest != request_digest:
        raise APIError(
            409,
            "idempotency key already used with different bundle",
            "invalid_request_error",
            "idempotency_conflict",
        )
    version = await session.get(ResourceVersion, prior.resource_version_id)
    resource = await require_resource(session, actor, version.resource_id, write=True)
    if version.deleted_at is not None:
        raise APIError(
            409, "previous import was deleted", "invalid_request_error", "resource_deleted"
        )
    return resource, version


@router.post("/api/bundles/import")
async def import_bundle(
    request: Request,
    idempotency_key: str = Header(min_length=1, max_length=128),
    actor: Actor = Depends(current_actor),
    session: AsyncSession = Depends(get_session),
    storage=Depends(get_storage),
):
    actor.require(actor.can_upload and actor.principal_id is not None, "导入资源")
    if request.headers.get("content-type", "").split(";", 1)[0] != "application/zip":
        raise APIError(
            415, "expected application/zip", "invalid_request_error", "bundle_content_type"
        )
    hasher = hashlib.sha256()
    total = 0
    with SpooledTemporaryFile(max_size=1024 * 1024, mode="w+b") as staged:
        async for chunk in request.stream():
            total += len(chunk)
            if total > MAX_ARCHIVE:
                raise APIError(
                    413, "bundle exceeds upload limit", "invalid_request_error", "bundle_too_large"
                )
            hasher.update(chunk)
            staged.write(chunk)
        try:
            verified = await asyncio.to_thread(read_bundle, staged)
        except BundleError as exc:
            raise _bundle_error(exc) from exc
    if verified.source["original"] == "missing":
        return JSONResponse(
            {
                "state": "source_missing",
                "source": verified.source,
                "error": {
                    "type": "invalid_request_error",
                    "code": "bundle_source_missing",
                    "message": "supply the original bytes before importing a usable resource",
                },
            },
            status_code=409,
        )

    # Org-scoped operation key; no collision with upload event keys or another organization.
    key = (
        "bundle:"
        + hashlib.sha256((actor.organization_id + "\x00" + idempotency_key).encode()).hexdigest()
    )
    request_digest = hasher.hexdigest()
    prior = await _prior(session, actor, key, request_digest)
    if prior:
        return _result(*prior, verified.source)

    resource_id, version_id = new_id(), new_id()
    prefix = f"bundles/{version_id}/"
    written = []
    try:
        objects = {**verified.files, "manifest.json": json_bytes(verified.manifest)}
        for name, content in objects.items():
            object_key = prefix + name
            # Register cleanup before put: a backend can write bytes and then fail.
            written.append(object_key)
            await storage.put(
                object_key,
                content,
                verified.source["mime"] if name == "source.bin" else "application/json",
            )
            if digest(await _get_bytes(storage, object_key, len(content))) != digest(content):
                raise APIError(
                    502,
                    "stored bundle failed digest verification",
                    "server_error",
                    "bundle_storage_mismatch",
                )

        # Reuse content only after supplied bytes have been verified. Imported layouts and
        # evidence stay in the version snapshot and cannot overwrite an existing parse/index.
        document = await session.scalar(
            select(Document)
            .where(
                Document.doc_id == verified.source["source_digest"][7:], Document.origin == "bundle"
            )
            .with_for_update()
        )
        if document is None:
            document = Document(
                id=new_id(),
                organization_id=actor.organization_id,
                uploaded_by=actor.principal_id,
                doc_id=verified.source["source_digest"][7:],
                origin="bundle",
                filename=verified.source["filename"],
                mime=verified.source["mime"],
                size_bytes=len(verified.files["source.bin"]),
                object_key=prefix + "source.bin",
            )
            session.add(document)
            await session.flush()
        elif document.deleted_at is not None or not document.object_key:
            document.deleted_at = None
            document.object_key = prefix + "source.bin"
        resource = Resource(
            id=resource_id,
            organization_id=actor.organization_id,
            owner_id=actor.principal_id,
            uploaded_by=actor.principal_id,
            display_name=verified.source["filename"],
            publication="private",
            # A remote raw ID must never resolve to a published local ancestor.
            # The full source tuple stays in the manifest; publication remains closed
            # until its remote permission dependency can be resolved by a trusted grant.
            copied_from="remote:"
            + hashlib.sha256(
                json_bytes(
                    [
                        verified.source["origin_node_id"],
                        verified.source["authority_node_id"],
                        verified.source["resource_id"],
                    ]
                )
            ).hexdigest()[:25],
        )
        session.add(resource)
        await session.flush()
        version = ResourceVersion(
            id=version_id,
            resource_id=resource.id,
            document_id=document.id,
            version_no=1,
            source_digest=verified.source["source_digest"][7:],
            filename=verified.source["filename"],
            size_bytes=len(verified.files["source.bin"]),
            parse_job_id=None,
            bundle_prefix=prefix,
        )
        session.add(version)
        await session.flush()
        if not await session.scalar(
            select(DocumentUpload.id).where(
                DocumentUpload.document_id == document.id,
                DocumentUpload.user_id == actor.principal_id,
            )
        ):
            session.add(DocumentUpload(document_id=document.id, user_id=actor.principal_id))
        session.add(
            UploadEvent(
                resource_version_id=version.id,
                actor_id=actor.principal_id,
                idempotency_key=key,
                request_digest=request_digest,
            )
        )
        await session.commit()
    except BaseException as exc:
        await session.rollback()
        for key_to_remove in written:
            try:
                await storage.delete(key_to_remove)
            except Exception:
                # An orphan is unreachable from any published version; never clean a
                # different import's prefix to compensate for a backend failure.
                pass
        if isinstance(exc, IntegrityError):
            prior = await _prior(session, actor, key, request_digest)
            if prior:
                return _result(*prior, verified.source)
            raise APIError(
                409,
                "concurrent import; retry with the same idempotency key",
                "invalid_request_error",
                "bundle_import_retry",
            ) from exc
        raise
    return JSONResponse(_result(resource, version, verified.source), status_code=201)
